//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNPM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuAnCNPM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AboutUs {
            get {
                object obj = ResourceManager.GetObject("AboutUs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string btnCancelOTP {
            get {
                return ResourceManager.GetString("btnCancelOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnContinueOTP {
            get {
                return ResourceManager.GetString("btnContinueOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnContinueOTP1 {
            get {
                return ResourceManager.GetString("btnContinueOTP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Design__1_ {
            get {
                object obj = ResourceManager.GetObject("Design (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diskette {
            get {
                object obj = ResourceManager.GetObject("diskette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap eyeClose {
            get {
                object obj = ResourceManager.GetObject("eyeClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap eyeOpen {
            get {
                object obj = ResourceManager.GetObject("eyeOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlagUS {
            get {
                object obj = ResourceManager.GetObject("FlagUS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlagVN {
            get {
                object obj = ResourceManager.GetObject("FlagVN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap handno {
            get {
                object obj = ResourceManager.GetObject("handno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap home__1_ {
            get {
                object obj = ResourceManager.GetObject("home (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright by Group 9.
        /// </summary>
        public static string lblBanQuyen {
            get {
                return ResourceManager.GetString("lblBanQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order list.
        /// </summary>
        public static string lblDanhsachdh {
            get {
                return ResourceManager.GetString("lblDanhsachdh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password ?.
        /// </summary>
        public static string lblForget {
            get {
                return ResourceManager.GetString("lblForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string lblHello {
            get {
                return ResourceManager.GetString("lblHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email to search for your account:.
        /// </summary>
        public static string lblInstruction {
            get {
                return ResourceManager.GetString("lblInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the confirmation code in your Email:.
        /// </summary>
        public static string lblInstructionOTP {
            get {
                return ResourceManager.GetString("lblInstructionOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password:.
        /// </summary>
        public static string lblInstructionOTP1 {
            get {
                return ResourceManager.GetString("lblInstructionOTP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREEN ORDERS - SUSTAINABLE TRADING.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to account:.
        /// </summary>
        public static string lblNoteOTP {
            get {
                return ResourceManager.GetString("lblNoteOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string lblPassnew {
            get {
                return ResourceManager.GetString("lblPassnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter new password:.
        /// </summary>
        public static string lblPassnewagain {
            get {
                return ResourceManager.GetString("lblPassnewagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation code !.
        /// </summary>
        public static string lblSelectionOTP {
            get {
                return ResourceManager.GetString("lblSelectionOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string lblThongbao {
            get {
                return ResourceManager.GetString("lblThongbao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important notice.
        /// </summary>
        public static string lblThongbaoImportant {
            get {
                return ResourceManager.GetString("lblThongbaoImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notification.
        /// </summary>
        public static string lblThongbaoNew {
            get {
                return ResourceManager.GetString("lblThongbaoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND ACCOUNT.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER CONFIRMATION CODE.
        /// </summary>
        public static string lblTitleOTP {
            get {
                return ResourceManager.GetString("lblTitleOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        public static string lblTitleOTP1 {
            get {
                return ResourceManager.GetString("lblTitleOTP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap left_arrow {
            get {
                object obj = ResourceManager.GetObject("left-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap left_chevron {
            get {
                object obj = ResourceManager.GetObject("left-chevron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap magnifying_glass_search {
            get {
                object obj = ResourceManager.GetObject("magnifying-glass-search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notification {
            get {
                object obj = ResourceManager.GetObject("notification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notification_bell {
            get {
                object obj = ResourceManager.GetObject("notification-bell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ringing {
            get {
                object obj = ResourceManager.GetObject("ringing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sortGiam {
            get {
                object obj = ResourceManager.GetObject("sortGiam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap techhive_icon {
            get {
                object obj = ResourceManager.GetObject("techhive_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string toolChude {
            get {
                return ResourceManager.GetString("toolChude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format.
        /// </summary>
        public static string toolDinhdangTime {
            get {
                return ResourceManager.GetString("toolDinhdangTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruct.
        /// </summary>
        public static string toolHuongdan {
            get {
                return ResourceManager.GetString("toolHuongdan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright.
        /// </summary>
        public static string toolItemSang {
            get {
                return ResourceManager.GetString("toolItemSang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string toolItemToi {
            get {
                return ResourceManager.GetString("toolItemToi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string toolLienhe {
            get {
                return ResourceManager.GetString("toolLienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string toolMuigio {
            get {
                return ResourceManager.GetString("toolMuigio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string toolTrangchu {
            get {
                return ResourceManager.GetString("toolTrangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string toolVechungtoi {
            get {
                return ResourceManager.GetString("toolVechungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txtFind {
            get {
                return ResourceManager.GetString("txtFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Account.
        /// </summary>
        public static string txtInput {
            get {
                return ResourceManager.GetString("txtInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter confirmation code.
        /// </summary>
        public static string txtInputOTP {
            get {
                return ResourceManager.GetString("txtInputOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtPass {
            get {
                return ResourceManager.GetString("txtPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string txtPassnew {
            get {
                return ResourceManager.GetString("txtPassnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter new password.
        /// </summary>
        public static string txtPassnewagain {
            get {
                return ResourceManager.GetString("txtPassnewagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] videoGlobal {
            get {
                object obj = ResourceManager.GetObject("videoGlobal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap z6523765316768_b4e94238b9f84f27e6672fffaaf1b7d0 {
            get {
                object obj = ResourceManager.GetObject("z6523765316768_b4e94238b9f84f27e6672fffaaf1b7d0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap z6523765316768_b4e94238b9f84f27e6672fffaaf1b7d01 {
            get {
                object obj = ResourceManager.GetObject("z6523765316768_b4e94238b9f84f27e6672fffaaf1b7d01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
